// <auto-generated />
namespace WebAcademia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ao_2003262147 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ao_2003262147));
        
        string IMigrationMetadata.Id
        {
            get { return "202003270047305_ao_2003262147"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
